---
- name: Deploy web application
  hosts: web
  become: true
  tasks:
    - name: Install Apache HTTP server
      apt:
        name: apache2
        state: present

    - name: Copy index.html
      copy:
        src: /tmp/index.html
        dest: /var/www/html/index.html

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: true
